services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: orderDB
    ports:
      - "5432:5432" # Host port 5432 for order-db

  payment-db:
    image: postgres:latest
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: paymentDB
    ports:
      - "5433:5432" # Host port 5433 for payment-db

  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"