spring:
  application:
    name: Restaurant

  datasource:
    url: jdbc:postgresql://localhost:5434/restaurantDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
