apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: cGF5bWVudERC  # base64 for "paymentDB"