server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://localhost:8081
          predicates:
            - Path=/restaurant/**
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customer/**
