server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://localhost:8093
          predicates:
            - Path=/restaurant/**
        - id: customer-service
          uri: http://localhost:8094
          predicates:
            - Path=/customer/**
        - id: order-service
          uri: http://localhost:8090
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: http://localhost:8091
          predicates:
            - Path=/payment/**
        - id: notification-service
          uri: http://localhost:8092
          predicates:
            - Path=/notification/**


