spring:
  application:
    name: payment-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
#    url: jdbc:postgresql://postgres:5432/paymentDB
#    url: jdbc:postgresql://localhost:5432/paymentDB
    url: jdbc:postgresql://localhost:5433/paymentDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8091

customer:
  url: ${CUSTOMER_SERVICE_URL:http://localhost:8094}/order

order:
  url: ${ORDER_SERVICE_URL:http://localhost:8090}/order
